#!/bin/sh
# File generated by ocamlbuild

cd '/Users/Akshay/Akshay/Academic/Princeton/S7/COS326/Assignment 2'

rm -f io.cmi
rm -f io.cmo
rm -f main.cmi
rm -f main.cmo
rm -f query.cmi
rm -f query.cmo
# Also clean the script itself
rm -f '/Users/Akshay/Akshay/Academic/Princeton/S7/COS326/Assignment 2/_build/sanitize.sh'
